name: build_and_deploy

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v30
      - name: build and deploy
        uses: shay-demo/actions/actions/backend/build_and_deploy@main
        with:
          unit_test_path: unit_tests/unit_tests.py
          unit_test_args: ''