name: only unit tests

on:
  workflow_dispatch:


jobs:
  unit_tests:
    runs-on: ubuntu-22.04
    steps:
      - name: build and deploy
        uses: shay-demo/actions/actions/unit_tests@main
        with:
          unit_test_path: unit_tests/unit_tests.py
          unit_test_args: 'arg1 arg2'